# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

tags = [
	"javascript",
	"java",
	"c#",
	"c",
	"php",
	"android",
	"ios",
	"jquery",
	"html",
	"c++",
	"mysql",
	"css",
	"sql",
	"asp.net",
	"objective-c",
	"swift",
	"ruby",
	"postgresql",
	"jade",
	"haml",
	"sass",
	"yaml",
	"arrays",
	"python",
	"ruby-on-rails",
	"ajax",
	"json",
	"xml",
	"linux",
	"angularjs",
	"django",
	"xcode",
	"nodejs",
	"wordpress",
	"git",
	"mongodb",
	"matlab",
	"scala",
	"api",
	"google",
	"cocoa-touch",
	"http",
	"spring",
	"unix",
	"lisp",
	"go",
	"rust",
	"ocaml",
	"curl",
	"emberjs",
	"reactjs",
	"model-view-controller",
	"asynchronous",
	"heroku",
	"twitter",
	"recursion",
	"emacs",
	"laravel",
	"joomla",
	"amazon-s3",
	"bootstrap",
	"twitter-bootstrap",
	"foundation",
	"material-design",
	"materialize",
	"clojure",
	"devise",
	"chrome",
	"redis",
	"cassandra",
	"oauth",
	"grunt",
	"gulp",
	"object-oriented",
	"unit-testing",
	"nginx",
	"docker",
	"devops"
]

tags.each do |tag|
	ActsAsTaggableOn::Tag.new(:name=> tag).save
end